site_name: Programowanie aplikacji geoinformatycznych (Python)
docs_dir: docs
repo_url: https://github.com/eo-agh/geoapps-python-course

copyright: Copyright 2024 Jakub Staszel KGiIS AGH

theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Strona gÅ‚Ã³wna: index.md
  - Podstawy programowania:
    - ğŸ‘½ Åšrodowisko lokalne: zaj0/srod-lok.md
    - ğŸŒ GIT - kontrola wersji: zaj01/git.md
  - Podstawy Pythona:
    - ğŸŒ ModuÅ‚y i przestrzenie nazw: zaj01/moduly_przestrzenie.md
    - ğŸŒ Podstawowe typy wbudowane: zaj01/typy_wbudowane.md
    - ğŸŒ Niespodziewane zachowania: zaj01/niespodziewane.md
    - ğŸŒ Instrukcje warunkowe i pÄ™tle: zaj01/instrukcje_petle.md
    - ğŸŒ Praca z plikami: zaj01/praca_z_plikami.md
    - ğŸŒğŸ“ Zadanie sprawdzajÄ…ce: zaj01/zadania_sprawdzajace.md
    - â„ï¸ Przypisania: zaj02/przypisania.md
  - PÄ™tle:
    - â„ï¸ WstÄ™p - pÄ™tle: zaj02/petle.md
    - â„ï¸ Listy skÅ‚adane: zaj02/listy_skladane.md
    - â„ï¸ Iteratory: zaj02/iteratory.md
  - Funkcje:
    - â„ï¸ WstÄ™p - funkcje: zaj02/funkcje.md
    - â„ï¸ Funkcje anonimowe - lambda: zaj02/lambda.md
    - â„ï¸ Generatory: zaj02/generatory.md
  - Programowanie obiektowe:
    - ğŸ¥• WstÄ™p - klasy i instancje: zaj03/klasy.md
    - ğŸ¥• Po co programowaÄ‡ obiektowo?: zaj03/obiektowe_poco.md
    - ğŸ¥• Dziedziczenie: zaj03/dziedziczenie.md
    - ğŸ¥• PrzeciÄ…Å¼anie operatorÃ³w: zaj03/przeciazanie.md
    - ğŸ¥•ğŸ“ Zadanie - przykÅ‚ad: zaj03/przyklad.md
    - ğŸ¥• NarzÄ™dzia introspekcji: zaj03/introspekcja.md
    - ğŸ¥• Abstrakcyjne klasy nadrzÄ™dne: zaj03/abstrakcyjne.md
    - ğŸ¥• Atrybuty pseudoprywatne: zaj03/pseudoprywatne.md
    - ğŸ¥• Rozszerzanie typÃ³w wbudowanych: zaj03/wbudowane.md
    - ğŸ¥• Sloty: zaj03/sloty.md
    - ğŸ¥• Rodzaje metod: zaj03/metody.md
    - ğŸ¥•ğŸ“ Zadania: zaj03/zadania.md
